name: basic_fastapi_ci

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
  test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
            - name: unit test
              run: |
                  echo 'running test'  
                  pytest -v
                  echo 'test completed'
  
  build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt
            - name: building project
              run: |
                  echo "Building project"
    
  run:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: building project
              run: |
                  echo "Building project"

  deploy:
        runs-on: ubuntu-latest
        needs: run
        steps:
            - name: checkout repository
              uses: actions/checkout@v5
            - name: installing python
              uses: actions/setup-python@v5
              with:
                   python-version: '3.13'
            - uses: actions/cache@v5
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
                restore-keys: |
                  ${{ runner.os }}-pip-
            - name: installing dependencis
              run: |
                   python -m pip install --upgrade pip
                   pip install -r requirements.txt 
            - name: building project
              run: |
                  echo "Building project"